'use client';
import Head from 'next/head'
import NavHome from '@/components/NavHome'
import {ColumnArticle, Title, SubTitle, InputStyle, ButtonStyle, LinkStyle } from '@/styles/home'
import { useEffect, useState } from 'react';
import { getProcess } from './api/home';
import Row from '@/components/Row';
import Column from '@/components/Column';

export default function Home() {
  const [ numberProcess, setNumberProcess ] = useState();
  const [ process, setProcess ] = useState();

  useEffect(() => {
    
  }, []);

  const fetchProcessData = async () => {
    try {
      const processData = await getProcess("00008323520184013202");
      setProcess(processData);
      console.log(processData)
    } catch (error) {
      console.error(error);
    }
  };

  

  const handleChangeProcessNumber = (value) => {
    console.log(value)
    setNumberProcess(value)
  }

  const handleClickSearch = () => {
    console.log('pesquisar',numberProcess)
    fetchProcessData()
  }
  console.log(process)
  return (
    <>
      <Head>
        <title>Processo livre</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavHome/>
      </div>
      
        <Column gap='60px' margin='100px'>
          <ColumnArticle>
            <Title>Processo Livre</Title>
            <SubTitle>Consulte processos a partir do número de forma gratuita!</SubTitle>
          </ColumnArticle> 
          <Column align='center' gap='12px'>
          <Row width='100%' align='center' justify='center' gap='12px'>
            <InputStyle type='number' placeholder='Digite o número do processo' value={numberProcess} onChange={(e) => handleChangeProcessNumber(e.target.value)}/>
            <ButtonStyle onClick={()=> handleClickSearch()}>Consultar</ButtonStyle>
          </Row> 

          <LinkStyle href="/faq">Deseja consultar de outra forma?</LinkStyle>
          </Column> 
        </Column>
    </>
  )
}
